version: "3.7"
services:
  api:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    image: admin-pro/api:1.0.0
    container_name: api
    user: "node"
    hostname: node
    ports:
      - "8080:8080"
    restart: "always"
    environment:
      - PORT=8080
      - host=db
      - user=postgres
      - password=admin123
      - database=postgres_typescript
    networks:
      - admin_pro_backend_default
  db:
    image: postgres:14.1
    container_name: postgresql
    ports: 
      - "5432:5432"
    restart: "always"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres_typescript
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - admin_pro_backend_default
  api_prod:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    image: admin-pro/api:1.0.0
    container_name: api
    user: "node"
    hostname: node
    ports:
      - "8080:8080"
    restart: "always"
    environment:
      - PORT=8080
      - host=db
      - user=postgres
      - password=admin123
      - database=postgres_typescript
    networks:
      - admin_pro_backend_default
volumes: 
     pgdata:
networks:
  admin_pro_backend_default:
    external: true